/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anwes
 */
public class Purchases extends javax.swing.JFrame {

    /**
     * Creates new form Purchases
     */
    public Purchases() {
        initComponents();
        connect();
    }
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_management_system", "root", "diya123");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        confirmpurchases = new javax.swing.JButton();
        addpurchases = new javax.swing.JButton();
        updatepurchases = new javax.swing.JButton();
        deletepurchases = new javax.swing.JButton();
        pid = new javax.swing.JTextField();
        item = new javax.swing.JTextField();
        constype = new javax.swing.JTextField();
        qty = new javax.swing.JSpinner();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalsales = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salestable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 100, 100));

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(242, 242, 242));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        confirmpurchases.setBackground(new java.awt.Color(0, 153, 0));
        confirmpurchases.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmpurchases.setForeground(new java.awt.Color(242, 242, 242));
        confirmpurchases.setText("Confirm");
        confirmpurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpurchasesActionPerformed(evt);
            }
        });

        addpurchases.setText("Add");
        addpurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpurchasesActionPerformed(evt);
            }
        });

        updatepurchases.setText("Update");
        updatepurchases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepurchasesMouseClicked(evt);
            }
        });

        deletepurchases.setText("Delete");
        deletepurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletepurchasesActionPerformed(evt);
            }
        });

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pidKeyPressed(evt);
            }
        });

        jLabel6.setText("Pid");

        jLabel1.setText("Item");

        jLabel2.setText("Consume Type");

        jLabel3.setText("Quantity");

        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Purchases Records");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total sales =");

        salestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pid", "Item", "Consume Type", "Quantity", "Price", "Total "
            }
        ));
        salestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salestableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salestable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addpurchases)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updatepurchases)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deletepurchases)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(item, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(pid, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(constype, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(qty)
                                    .addComponent(price))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(confirmpurchases, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(constype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpurchases, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addpurchases)
                    .addComponent(updatepurchases)
                    .addComponent(deletepurchases)
                    .addComponent(jLabel7)
                    .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void confirmpurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpurchasesActionPerformed

        try {
            // TODO add your handling code here:
            PreparedStatement pst1;
            pst1 = con.prepareStatement("update `pharmacy_management_system`.`items` set `Quantity` = Quantity - ?, `Price` = Price - ? where `Pid` = ?");
            for(int i=0; i<salestable.getRowCount();i++)
            {
                String productid = salestable.getValueAt(i, 0).toString();
                String qty1 = salestable.getValueAt(i, 3).toString();
                String total = salestable.getValueAt(i, 5).toString();
                pst1.setString(1,qty1);
                pst1.setString(2, total);
                pst1.setString(3,productid);
                pst1.executeUpdate();
            }

            DateTimeFormatter dt = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            String date = dt.format(now);
            int lastid=0;

            String subtotal1 = totalsales.getText();
            PreparedStatement pst2 = con.prepareStatement("insert into `pharmacy_management_system`.`sales` (`date`,`subtotal`) values (?,?); ", Statement.RETURN_GENERATED_KEYS);
            pst2.setString(1, date);
            pst2.setString(2,subtotal1);

            pst2.executeUpdate();
            ResultSet rs1=pst2.getGeneratedKeys();
            if(rs1.next())
            {
                lastid=rs1.getInt(1);
            }
            PreparedStatement pst3 = con.prepareStatement("insert into `pharmacy_management_system`.`salesitem` (`salesid`,`item`,`consumetype`,`quantity`,`price`,`total`) values (?,?,?,?,?,?); ");
            String item1;
            String consumetype;
            String quantity;
            String price1;
            String total;
            for(int i=0; i<salestable.getRowCount();i++)
            {
                item1=salestable.getValueAt(i, 1).toString();
                consumetype=salestable.getValueAt(i, 2).toString();
                quantity=salestable.getValueAt(i, 3).toString();
                price1=salestable.getValueAt(i, 4).toString();
                total=salestable.getValueAt(i, 5).toString();

                pst3.setInt(1,lastid );
                pst3.setString(2,item1 );
                pst3.setString(3,consumetype );
                pst3.setString(4,quantity);
                pst3.setString(5,price1 );
                pst3.setString(6,total );
                pst3.executeUpdate();
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this,"Sales recorded");

    }//GEN-LAST:event_confirmpurchasesActionPerformed

    private void addpurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpurchasesActionPerformed
        // TODO add your handling code here:
        addsales();
    }//GEN-LAST:event_addpurchasesActionPerformed

    private void updatepurchasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepurchasesMouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)salestable.getModel();
        int selected = salestable.getSelectedRow();
        int quan = (int)qty.getValue();
        df.setValueAt(quan, selected, 3);
        double cost = Double.parseDouble(price.getText());
        int qty1 = (int)qty.getValue();
        double tot = cost * qty1;
        df.setValueAt(tot, selected, 5);
        double sum = 0.0;
        for(int i=0 ; i<salestable.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(salestable.getValueAt(i, 5).toString());
        }
        totalsales.setText(String.valueOf(sum));
        pid.setText("");
        item.setText("");
        constype.setText("");
        qty.setValue(0);
        price.setText("");
    }//GEN-LAST:event_updatepurchasesMouseClicked

    private void deletepurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletepurchasesActionPerformed
        // TODO add your handling code here:
        df = (DefaultTableModel)salestable.getModel();
        int selected = salestable.getSelectedRow();
        if(selected >= 0)
        {
            df.removeRow(selected);
            JOptionPane.showMessageDialog(null, "Item Deleted");
        }
    }//GEN-LAST:event_deletepurchasesActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pidActionPerformed

    private void pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {

            sales();
        }
    }//GEN-LAST:event_pidKeyPressed

    private void salestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salestableMouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)salestable.getModel();
        int selected = salestable.getSelectedRow();
        pid.setText(df.getValueAt(selected,0 ).toString());
        item.setText(df.getValueAt(selected,1).toString());
        constype.setText(df.getValueAt(selected,2 ).toString());
        qty.setValue(df.getValueAt(selected,3 ));
        price.setText(df.getValueAt(selected,4).toString());

    }//GEN-LAST:event_salestableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpurchases;
    private javax.swing.JButton close;
    private javax.swing.JButton confirmpurchases;
    private javax.swing.JTextField constype;
    private javax.swing.JButton deletepurchases;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField price;
    private javax.swing.JSpinner qty;
    private javax.swing.JTable salestable;
    private javax.swing.JTextField totalsales;
    private javax.swing.JButton updatepurchases;
    // End of variables declaration//GEN-END:variables
}
