/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;
import java.awt.event.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anwes
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        connect();
    }
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_management_system", "root", "diya123");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void sales()
    {
        
        try {
            String Pid = pid.getText();
            pst = con.prepareStatement("select * from `pharmacy_management_system`.`items` where `Pid` = ?");
            pst.setString(1, Pid);
            ResultSet rs = pst.executeQuery();
           if(rs.next() == false)
           {
               JOptionPane.showMessageDialog(this,"Product code not found");
           }
           else
           {
               String item1 = rs.getString("Item");
               String constype1 = rs.getString("Consume Type");
               Double cost = rs.getDouble("Price")/rs.getInt("Quantity");
               item.setText(item1);
               constype.setText(constype1);
               String costconversion = String.valueOf(cost);
               price.setText(costconversion);
               
          }
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void addsales()
    {
         
        try {
            double cost = Double.parseDouble(price.getText());
            int qty1 = (int)qty.getValue();
            double tot = cost * qty1;
            int qtyvalue=0;
            
            df = (DefaultTableModel)salestable.getModel();
            String Pid = pid.getText();
            pst = con.prepareStatement("select `Quantity` from `pharmacy_management_system`.`items` where `Pid` = ?");
            pst.setString(1, Pid);
            ResultSet rs = pst.executeQuery();
            if(rs.next() == false)
           {
               JOptionPane.showMessageDialog(this,"Product code not found");
           }
            else
            {
            qtyvalue = rs.getInt("Quantity");
            }
            System.out.println(qtyvalue);
            if(qty1<=0)
            {
                JOptionPane.showMessageDialog(this,"Quantity not mentioned");
            }
            else if(qty1>qtyvalue)
            {
                JOptionPane.showMessageDialog(this,"Item Out Of Stock");
            }
            else
            {
                df.addRow(new Object[]
                {
                    pid.getText(),
                    item.getText(),
                    constype.getText(),
                    qty.getValue(),
                    price.getText(),
                    String.valueOf(tot)
                });
                
                double sum = 0.0;
                for(int i=0 ; i<salestable.getRowCount(); i++)
                {
                    sum = sum + Double.parseDouble(salestable.getValueAt(i, 5).toString());
                }
                totalsales.setText(String.valueOf(sum));
                pid.setText("");
                item.setText("");
                constype.setText("");
                qty.setValue(0);
                price.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salestable = new javax.swing.JTable();
        constype = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addsales = new javax.swing.JButton();
        updatesales = new javax.swing.JButton();
        deletesales = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        qty = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        totalsales = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        confirmsales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Item");

        jLabel2.setText("Consume Type");

        salestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pid", "Item", "Consume Type", "Quantity", "Price", "Total "
            }
        ));
        salestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salestableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salestable);

        jLabel3.setText("Quantity");

        jLabel4.setText("Price");

        addsales.setText("Add");
        addsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsalesActionPerformed(evt);
            }
        });

        updatesales.setText("Update");
        updatesales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatesalesMouseClicked(evt);
            }
        });

        deletesales.setText("Delete");
        deletesales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesalesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Sale Records");

        jLabel6.setText("Pid");

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pidKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total sales =");

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(242, 242, 242));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        confirmsales.setBackground(new java.awt.Color(0, 153, 0));
        confirmsales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmsales.setForeground(new java.awt.Color(242, 242, 242));
        confirmsales.setText("Confirm");
        confirmsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmsalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addsales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updatesales)
                        .addGap(12, 12, 12)
                        .addComponent(deletesales))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(item, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(constype, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qty, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(confirmsales, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(constype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addsales)
                            .addComponent(updatesales)
                            .addComponent(deletesales)
                            .addComponent(jLabel7)
                            .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmsales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletesalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesalesActionPerformed
        // TODO add your handling code here:
            df = (DefaultTableModel)salestable.getModel();
            int selected = salestable.getSelectedRow();
            if(selected >= 0)
            {
                df.removeRow(selected);
                JOptionPane.showMessageDialog(null, "Item Deleted");
            }       
    }//GEN-LAST:event_deletesalesActionPerformed

    private void addsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsalesActionPerformed
        // TODO add your handling code here:
        addsales();
    }//GEN-LAST:event_addsalesActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pidActionPerformed

    private void pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
            sales();
        }
    }//GEN-LAST:event_pidKeyPressed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void confirmsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmsalesActionPerformed
        
        try {
            // TODO add your handling code here:
            PreparedStatement pst1;
            pst1 = con.prepareStatement("update `pharmacy_management_system`.`items` set `Quantity` = Quantity - ?, `Price` = Price - ? where `Pid` = ?");
            for(int i=0; i<salestable.getRowCount();i++)
            {
                String productid = salestable.getValueAt(i, 0).toString();
                String qty1 = salestable.getValueAt(i, 3).toString();
                String total = salestable.getValueAt(i, 5).toString();
                pst1.setString(1,qty1);
                pst1.setString(2, total);
                pst1.setString(3,productid);
                pst1.executeUpdate();
             }
            
            DateTimeFormatter dt = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            String date = dt.format(now);
            int lastid=0;
            
            String subtotal1 = totalsales.getText();
            PreparedStatement pst2 = con.prepareStatement("insert into `pharmacy_management_system`.`sales` (`date`,`subtotal`) values (?,?); ", Statement.RETURN_GENERATED_KEYS);
            pst2.setString(1, date);
            pst2.setString(2,subtotal1);
            
            pst2.executeUpdate();
            ResultSet rs1=pst2.getGeneratedKeys();
            if(rs1.next())
            {
                lastid=rs1.getInt(1);
            }
            PreparedStatement pst3 = con.prepareStatement("insert into `pharmacy_management_system`.`salesitem` (`salesid`,`item`,`consumetype`,`quantity`,`price`,`total`) values (?,?,?,?,?,?); ");
            String item1;
            String consumetype;
            String quantity;
            String price1;
            String total;
            for(int i=0; i<salestable.getRowCount();i++)
            {
            item1=salestable.getValueAt(i, 1).toString();
            consumetype=salestable.getValueAt(i, 2).toString();
            quantity=salestable.getValueAt(i, 3).toString();
            price1=salestable.getValueAt(i, 4).toString();
            total=salestable.getValueAt(i, 5).toString();
            
            pst3.setInt(1,lastid );
            pst3.setString(2,item1 );
            pst3.setString(3,consumetype );
            pst3.setString(4,quantity);
            pst3.setString(5,price1 );
            pst3.setString(6,total );
            pst3.executeUpdate();
            }     
        }
        catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this,"Sales recorded");
        
        
    }//GEN-LAST:event_confirmsalesActionPerformed

    private void updatesalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatesalesMouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)salestable.getModel();
        int selected = salestable.getSelectedRow();
        int quan = (int)qty.getValue();
        df.setValueAt(quan, selected, 3);
        double cost = Double.parseDouble(price.getText());
            int qty1 = (int)qty.getValue();
            double tot = cost * qty1;
            df.setValueAt(tot, selected, 5);
            double sum = 0.0;
                for(int i=0 ; i<salestable.getRowCount(); i++)
                {
                    sum = sum + Double.parseDouble(salestable.getValueAt(i, 5).toString());
                }
                totalsales.setText(String.valueOf(sum));
                pid.setText("");
                item.setText("");
                constype.setText("");
                qty.setValue(0);
                price.setText("");   
    }//GEN-LAST:event_updatesalesMouseClicked

    private void salestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salestableMouseClicked
        // TODO add your handling code here:
            df = (DefaultTableModel)salestable.getModel();
            int selected = salestable.getSelectedRow();
            pid.setText(df.getValueAt(selected,0 ).toString());
            item.setText(df.getValueAt(selected,1).toString());
            constype.setText(df.getValueAt(selected,2 ).toString());
            qty.setValue(df.getValueAt(selected,3 ));
            price.setText(df.getValueAt(selected,4).toString());
            
            
    }//GEN-LAST:event_salestableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsales;
    private javax.swing.JButton close;
    private javax.swing.JButton confirmsales;
    private javax.swing.JTextField constype;
    private javax.swing.JButton deletesales;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField price;
    private javax.swing.JSpinner qty;
    private javax.swing.JTable salestable;
    private javax.swing.JTextField totalsales;
    private javax.swing.JButton updatesales;
    // End of variables declaration//GEN-END:variables
}
